### ISSUE TITLE
lol and lola

### ISSUE THREAD

**Issue by kristenmills** [nickserv/sane-defaults#1]
needed in your gitconfig.

lol = log --graph --decorate --pretty=oneline --abbrev-commit
lola = log --graph --decorate --pretty=oneline --abbrev-commit --all

**Comment by nickserv** [comment]
Thanks for the suggestion, but I don't want to change functionality like this for sane defaults (see goals).

I will consider it for my own personal configs, though. Especially for the abbreviated names. Pretty legit.
